name: azure-adf-cicd-project

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install ADF Utilities package
        run: npm install


      - name: Validate ADF resources
        run: npm run build validate ${{ github.workspace }}/ADF_Pipeline/Ingestion/ /subscriptions/3915c783-2b04-4f6f-94d4-8d3ac1d3deb5/resourceGroups/Ravi_RG/providers/Microsoft.DataFactory/factories/practiceadf20252025


      - name: Validate and Generate ARM template
        run: npm run build export ${{ github.workspace }}/ADF_Pipeline/Ingestion/ /subscriptions/3915c783-2b04-4f6f-94d4-8d3ac1d3deb5/resourceGroups/Ravi_RG/providers/Microsoft.DataFactory/factories/practiceadf20252025 ExportedArmTemplate


      - name: Upload ARM template artifact
        uses: actions/upload-artifact@v4
        with:
          name: ExportedArmTemplate
          path: ${{ github.workspace }}/build/ExportedArmTemplate

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: ExportedArmTemplate

      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: a045faaf-ea6b-4bf8-86d0-6f932f46cf34
          tenant-id: 5f6ff5cb-7984-4efe-a3ef-6d2cfb07684a
          subscription-id: 3915c783-2b04-4f6f-94d4-8d3ac1d3deb5
          enable-AzPSSession: true

      - name: Deploy to Data Factory
        uses: Azure/data-factory-deploy-action@v1.2.0
        with:
          resourceGroupName: Ravi_RG
          dataFactoryName: practiceadf20252025
          armTemplateFile: ARMTemplateForFactory.json
          armTemplateParametersFile: ARMTemplateParametersForFactory.json
          # additionalParameters: 'factoryName=Test-ADF-111' # optional, if needed for dynamic replacements
