name: Google

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1.4.6
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: Upload Linked Templates to Storage Account
        run: |
          az storage container create --name templates --account-name datalake31052025
          az storage blob upload --container-name link_templates --file ./linked-template.json --name linked-template.json --account-name datalake31052025
          SAS_TOKEN=$(az storage container generate-sas --name templates --account-name $datalake31052025 --permissions r --expiry $(date -u +%Y-%m-%dT%H:%M:%SZ -d "+1 hour") --output tsv)
          echo "SAS_TOKEN=$SAS_TOKEN" >> $GITHUB_ENV

      - name: Deploy Main ARM Template
        uses: azure/arm-deploy@v1
        with:
          resourceGroupName: datalake31052025
          template: ./main-template.json
          parameters: linkedTemplateUri='https://datalake31052025.blob.core.windows.net/templates/linked-template.json?${{ env.SAS_TOKEN }}'