name: Google

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1.4.6
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: Upload Linked Templates to Storage Account
        run: |
          az storage blob upload --account-name datalake31052025 -d "xyz" -s 'devu/linkedTemplates/' --overwrite


      - name: Deploy Main ARM Template
        uses: azure/arm-deploy@v1
        with:
          resourceGroupName: datalake31052025
          template: ./main-template.json
          parameters: linkedTemplateUri='https://datalake31052025.blob.core.windows.net/templates/linked-template.json?${{ env.SAS_TOKEN }}'