name: Azure Storage Emulator Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test-azure-storage:
    runs-on: ubuntu-latest
    
    services:
      azurite:
        image: mcr.microsoft.com/azure-storage/azurite
        ports:
          - 10000:10000  # Blob service
          - 10001:10001  # Queue service  
          - 10002:10002  # Table service
        options: >-
          --health-cmd "curl -f http://localhost:10000/"
          --health-interval 30s
          --health-timeout 10s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm install @azure/storage-blob @azure/identity

    - name: Create test file
      run: |
        echo "This is a test file for Azure Storage upload" > test-file.txt
        echo "Created at $(date)" >> test-file.txt

    - name: Test Azure Storage operations
      run: node test-storage.js
      env:
        AZURE_STORAGE_CONNECTION_STRING: "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;"
        
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: storage-test-results
        path: |
          test-file.txt
          storage-test-output.txt