name: Azure Emulator
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker run -d -p 10000:10000 mcr.microsoft.com/azure-storage/azurite
      - run: dotnet test